### ISSUE TITLE
Newest version does not run after ESM change

### ISSUE THREAD

**Issue by Nef10** [BetaHuhn/repo-file-sync-action#289]
### 🐞 Describe the bug

```
2023-01-07T17:44:55.0909616Z ##[endgroup]
2023-01-07T17:44:55.1588432Z undefined:1
2023-01-07T17:44:55.1589393Z require
2023-01-07T17:44:55.1589809Z ^
2023-01-07T17:44:55.1590021Z 
2023-01-07T17:44:55.1590612Z ReferenceError: require is not defined in ES module scope, you can use import instead
2023-01-07T17:44:55.1592294Z This file is being treated as an ES module because it has a '.js' file extension and '/home/runner/work/_actions/BetaHuhn/repo-file-sync-action/v1/dist/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
2023-01-07T17:44:55.1593995Z     at eval (eval at 539 (file:///home/runner/work/_actions/BetaHuhn/repo-file-sync-action/v1/dist/index.js:1:41342), <anonymous>:1:1)
2023-01-07T17:44:55.1594984Z     at Object.539 (file:///home/runner/work/_actions/BetaHuhn/repo-file-sync-action/v1/dist/index.js:1:41342)
2023-01-07T17:44:55.1595948Z     at __nccwpck_require__ (file:///home/runner/work/_actions/BetaHuhn/repo-file-sync-action/v1/dist/index.js:1:42491)
2023-01-07T17:44:55.1596987Z     at file:///home/runner/work/_actions/BetaHuhn/repo-file-sync-action/v1/dist/index.js:1:42877
2023-01-07T17:44:55.1597862Z     at file:///home/runner/work/_actions/BetaHuhn/repo-file-sync-action/v1/dist/index.js:1:47000
2023-01-07T17:44:55.1598624Z     at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
2023-01-07T17:44:55.1599193Z     at async Promise.all (index 0)
2023-01-07T17:44:55.1599766Z     at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
2023-01-07T17:44:55.1600397Z     at async loadESM (node:internal/process/esm_loader:88:5)
2023-01-07T17:44:55.1601027Z     at async handleMainPromise (node:internal/modules/run_main:65:12)
```

### 📚 To reproduce

Just try to run it

### 💡 Expected behavior

It syncs

### ⚙️ Environment

Version `69868d68f6969b7a599ca783823eb29e3b3679e8`

### 📋 Additional context

See https://github.com/Nef10/common-swift-package/actions/runs/3863217212/jobs/6585266148

**Comment by BetaHuhn** [comment]
The latest changes worked in my testing. Will take a look at what's causing this.

**Comment by Alshadex** [comment]
Getting same error.

**Comment by BetaHuhn** [comment]
The issue should be fixed with [v1.20.1](https://github.com/BetaHuhn/repo-file-sync-action/releases/tag/v1.20.1). Sorry for the inconvenience!

Seems like I accidentally used an old git tag when testing so I actually tested the previous version before the esm changes. The issue itself was caused by wrong imports.

**Comment by phnx47** [comment]
It is working now!

**Comment by Nef10** [comment]
Works now :) Thanks!
